name: ktlint
on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Gradle
        uses: actions/cache@v1
        env:
          cache-name: cache-gradle-gradlew
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            ${{ runner.os }}-
      - name: Run ktlintCheck
        run: ./gradlew ktlintGithub --githubOAuth=${{ secrets.github_token }} --githubPullRequest=${{ github.event.number }}
      - name: Install reviewdog
        run: |
          wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b /usr/local/bin/
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.36.0/ktlint
          chmod a+x ktlint
          mv ktlint /usr/local/bin/
      - name: Run reviewdog
        with:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ktlint --relative --reporter=checkstyle | reviewdog -f=checkstyle -name="ktlint" -reporter="github-pr-review" -level="error"