name: ktlint
on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ktlint
        uses: mirror-kt/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning