name: ktlint
on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Gradle
        uses: actions/cache@v1
        env:
          cache-name: cache-gradle-gradlew
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            ${{ runner.os }}-
      - name: Run ktlintCheck
        run: ./gradlew ktlintGithub --githubOAuth=${{ secrets.github_token }} --githubPullRequest=${{ github.event.number }}
